# Generated by Django 4.2.7 on 2024-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('problem', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'contact us',
            },
        ),
    ]
